### PR TITLE
full page content

### PR DESCRIPTION
**Pull request by schulle4u**
* Added `<content:encoded>` to RSS output. 
* `dc:creator` as author information for RSS items. This is less restrictive and doesn't require an email address.

### CODE REVIEW

**Comment by markseu** [comment]
Thank you. 

Please send me just the feed.php, I take take of the rest when I merge it.

**Comment by schulle4u** [comment]
Could you please make this commit manually? GitHub don't want to show me the revert options for my last 2 commits for some reason, maybe because the pull request is already opened. 

https://github.com/schulle4u/yellow-plugins/blob/schulle4u-patch-1/feed/feed.php

I can also send you a mail if you want. 

Thanks

**Comment by markseu** [comment]
Done. Let's try it out some days on your blog and then I merge it. 😄

**Comment by schulle4u** [comment]
The new feed is [already online](https://www.robbenradio.de/home/blog/feed/page:feed.xml). 

What I'm still trying to figure out is why `$this->yellow->page->get("Author")` doesn't show the page author as expected. On my blog it shows the global author setting from config.ini instead, even if page author is different. Maybe a bug?

**Comment by markseu** [comment]
Found it, should be working now.

**Comment by schulle4u** [comment]
Thanks Mark, page author is working now. I'm afraid I'll have to read the API documentation again to fully understand the differences between the various API calls. 

BTW, I just tested what happens if a page has no author in it's meta data. The feed then simply displays the webmaster as a fallback. Very clever, this saves us additional plugin work. 

Time for other stuff now, further testing tomorrow...

**Comment by schulle4u** [comment]
If a page contains relative URL references (e.g. `[Link Name](/page)`), these URL's are relative in the feed output as well. Clicking them in feed readers therefore could result in errors, assuming the reader isn't able to automatically add the server's hostname. 

The W3C feed validator recommends to avoid relative URL references in `<content:encoded>`. [Here is an example)(https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.powerradio4u.de%2Ffeed%2Fpage%3Afeed.xml). 

What do you think, should we implement a workaround for this minor problem or just leave this in webmaster's responsibility? I'd prefer last.

**Comment by markseu** [comment]
Not sure if we can implement a workaround, at least not a quick one.

I tested a full content RSS feed with Firefox, all links are working there.

**Comment by schulle4u** [comment]
I tested this in [Miniflux](http://miniflux.net) and it can handle relative URLs as well. So I think we can safely ignore the W3C recommendations. 

BTW, your merge commit reverted a small change I've made in feed.php a few days ago. Was this accedentally?

**Comment by markseu** [comment]
Oh sorry when I deleted something in my last commit... I resolved a merge conflict.

**Comment by schulle4u** [comment]
Indeed, I wanted to have the full URL as page break link. No problem, code restored. :)

If there's nothing else you would like to implement or test, I think we can release the new version. On my both sites everything works as expected.

**Comment by schulle4u** [comment]
Sorry Mark, I didn't noticed your other modifications. Should be all up-to-date now. Github can be straining sometimes.

**Comment by markseu** [comment]
Thanks Steffen. I update the blog plugin, so that they both behave the same way, then I'll merge.

**Comment by markseu** [comment]
Done, thanks for your help 👍

**Pull request merged**
